-- DROP TABLE IF EXISTS listings; -- If we have some update in the table

create table if not exists listings (
	id numeric(50),
	listing_url text,
	scrape_id numeric(30),
	last_scraped date,
	source text,
	name text,
	description text,
	neighborhood_overview text,
	picture_url text,
	host_id numeric(50),
	host_url text,
	host_profile_id numeric(20),
	host_profile_url text,
	host_name text,
	host_since date,
	hosts_time_as_user_years numeric(20),
	hosts_time_as_user_months numeric(20),
	hosts_time_as_host_years numeric(20),
	hosts_time_as_host_months numeric(20),
	host_location text,
	host_about text,
	host_response_time text,
	host_response_rate numeric(20),
	host_acceptance_rate numeric(20),
	host_is_superhost boolean,
	host_thumbnail_url text,
	host_picture_url text,
	host_neighbourhood text,
	host_listings_count numeric(20, 2),
	host_total_listings_count numeric(10),
	host_verifications text,
	host_has_profile_pic boolean,
	host_identity_verified boolean,
	neighbourhood text,
	neighbourhood_cleansed text,
	neighbourhood_group_cleansed text,
	latitude numeric(20,2),
	longitude numeric(20,2),
	property_type text,
	room_type text,
	accommodates numeric(10),
	bathrooms numeric(20,2),
	bathrooms_text text,
	bedrooms numeric(20),
	beds numeric(20),
	amenities text,
	price numeric(20),
	price_quote_checkin_date date,
	price_quote_checkout_date date,
	price_quote_total_price numeric(20),
	price_quote_price_per_night numeric(20),
	price_quote_raw json,
	minimum_nights numeric(20),
	maximum_nights numeric(20),
	minimum_minimum_nights numeric(20),
	maximum_minimum_nights numeric(20),
	minimum_maximum_nights numeric(20),
	maximum_maximum_nights numeric(20),
	minimum_nights_avg_ntm numeric(20),
	maximum_nights_avg_ntm numeric(20),
	calendar_updated date,
	has_availability boolean,
	availability_30 numeric(20),
	availability_60 numeric(20),
	availability_90 numeric(20),
	availability_365 numeric(20),
	calendar_last_scraped date,
	number_of_reviews numeric(20),
	number_of_reviews_ltm numeric(20),
	number_of_reviews_l30d numeric(20),
	availability_eoy numeric(20),
	number_of_reviews_ly numeric(20),
	estimated_occupancy_l365d numeric(20),
	estimated_revenue_l365d numeric(20),
	first_review date,
	last_review	date,
	review_scores_rating numeric(20,2),
	review_scores_accuracy numeric(20,2),
	review_scores_cleanliness numeric(20,2),
	review_scores_checkin numeric(20,2),
	review_scores_communication numeric(20,2),
	review_scores_location numeric(20,2),
	review_scores_value numeric(20,2),
	license text,
	instant_bookable boolean,
	calculated_host_listings_count numeric(20,2),
	calculated_host_listings_count_entire_homes numeric(20,2),
	calculated_host_listings_count_private_rooms numeric(20,2),
	calculated_host_listings_count_shared_rooms	numeric(20,2),
	reviews_per_month numeric(20,2),
	
	primary key (id)
) ;


--ALTER TABLE listings
--ADD CONSTRAINT listings_pkey PRIMARY KEY (id);







